/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Admin1776RouteImport } from './routes/admin1776'
import { Route as BatteriesRouteImport } from './routes/batteries'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FloridaRouteImport } from './routes/florida'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SolarRouteImport } from './routes/solar'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as FloridaCharlotteCountyRouteImport } from './routes/florida.charlotte-county'
import { Route as FloridaCollierCountyRouteImport } from './routes/florida.collier-county'
import { Route as FloridaLeeCountyRouteImport } from './routes/florida.lee-county'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Admin1776Route = Admin1776RouteImport.update({
  id: '/admin1776',
  path: '/admin1776',
  getParentRoute: () => rootRouteImport,
} as any)
const BatteriesRoute = BatteriesRouteImport.update({
  id: '/batteries',
  path: '/batteries',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FloridaRoute = FloridaRouteImport.update({
  id: '/florida',
  path: '/florida',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SolarRoute = SolarRouteImport.update({
  id: '/solar',
  path: '/solar',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const FloridaCharlotteCountyRoute = FloridaCharlotteCountyRouteImport.update({
  id: '/charlotte-county',
  path: '/charlotte-county',
  getParentRoute: () => FloridaRoute,
} as any)
const FloridaCollierCountyRoute = FloridaCollierCountyRouteImport.update({
  id: '/collier-county',
  path: '/collier-county',
  getParentRoute: () => FloridaRoute,
} as any)
const FloridaLeeCountyRoute = FloridaLeeCountyRouteImport.update({
  id: '/lee-county',
  path: '/lee-county',
  getParentRoute: () => FloridaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin1776': typeof Admin1776Route
  '/batteries': typeof BatteriesRoute
  '/calculator': typeof CalculatorRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/florida': typeof FloridaRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/solar': typeof SolarRoute
  '/terms': typeof TermsRoute
  '/florida/charlotte-county': typeof FloridaCharlotteCountyRoute
  '/florida/collier-county': typeof FloridaCollierCountyRoute
  '/florida/lee-county': typeof FloridaLeeCountyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin1776': typeof Admin1776Route
  '/batteries': typeof BatteriesRoute
  '/calculator': typeof CalculatorRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/florida': typeof FloridaRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/solar': typeof SolarRoute
  '/terms': typeof TermsRoute
  '/florida/charlotte-county': typeof FloridaCharlotteCountyRoute
  '/florida/collier-county': typeof FloridaCollierCountyRoute
  '/florida/lee-county': typeof FloridaLeeCountyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin1776': typeof Admin1776Route
  '/batteries': typeof BatteriesRoute
  '/calculator': typeof CalculatorRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/florida': typeof FloridaRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/solar': typeof SolarRoute
  '/terms': typeof TermsRoute
  '/florida/charlotte-county': typeof FloridaCharlotteCountyRoute
  '/florida/collier-county': typeof FloridaCollierCountyRoute
  '/florida/lee-county': typeof FloridaLeeCountyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin1776'
    | '/batteries'
    | '/calculator'
    | '/company'
    | '/contact'
    | '/florida'
    | '/privacy'
    | '/solar'
    | '/terms'
    | '/florida/charlotte-county'
    | '/florida/collier-county'
    | '/florida/lee-county'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin1776'
    | '/batteries'
    | '/calculator'
    | '/company'
    | '/contact'
    | '/florida'
    | '/privacy'
    | '/solar'
    | '/terms'
    | '/florida/charlotte-county'
    | '/florida/collier-county'
    | '/florida/lee-county'
  id:
    | '__root__'
    | '/'
    | '/admin1776'
    | '/batteries'
    | '/calculator'
    | '/company'
    | '/contact'
    | '/florida'
    | '/privacy'
    | '/solar'
    | '/terms'
    | '/florida/charlotte-county'
    | '/florida/collier-county'
    | '/florida/lee-county'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Admin1776Route: typeof Admin1776Route
  BatteriesRoute: typeof BatteriesRoute
  CalculatorRoute: typeof CalculatorRoute
  CompanyRoute: typeof CompanyRoute
  ContactRoute: typeof ContactRoute
  FloridaRoute: typeof FloridaRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SolarRoute: typeof SolarRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin1776': {
      id: '/admin1776'
      path: '/admin1776'
      fullPath: '/admin1776'
      preLoaderRoute: typeof Admin1776RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batteries': {
      id: '/batteries'
      path: '/batteries'
      fullPath: '/batteries'
      preLoaderRoute: typeof BatteriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/florida': {
      id: '/florida'
      path: '/florida'
      fullPath: '/florida'
      preLoaderRoute: typeof FloridaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solar': {
      id: '/solar'
      path: '/solar'
      fullPath: '/solar'
      preLoaderRoute: typeof SolarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/florida/charlotte-county': {
      id: '/florida/charlotte-county'
      path: '/charlotte-county'
      fullPath: '/florida/charlotte-county'
      preLoaderRoute: typeof FloridaCharlotteCountyRouteImport
      parentRoute: typeof FloridaRoute
    }
    '/florida/collier-county': {
      id: '/florida/collier-county'
      path: '/collier-county'
      fullPath: '/florida/collier-county'
      preLoaderRoute: typeof FloridaCollierCountyRouteImport
      parentRoute: typeof FloridaRoute
    }
    '/florida/lee-county': {
      id: '/florida/lee-county'
      path: '/lee-county'
      fullPath: '/florida/lee-county'
      preLoaderRoute: typeof FloridaLeeCountyRouteImport
      parentRoute: typeof FloridaRoute
    }
  }
}

interface FloridaRouteChildren {
  FloridaCharlotteCountyRoute: typeof FloridaCharlotteCountyRoute
  FloridaCollierCountyRoute: typeof FloridaCollierCountyRoute
  FloridaLeeCountyRoute: typeof FloridaLeeCountyRoute
}

const FloridaRouteChildren: FloridaRouteChildren = {
  FloridaCharlotteCountyRoute: FloridaCharlotteCountyRoute,
  FloridaCollierCountyRoute: FloridaCollierCountyRoute,
  FloridaLeeCountyRoute: FloridaLeeCountyRoute,
}

const FloridaRouteWithChildren =
  FloridaRoute._addFileChildren(FloridaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Admin1776Route: Admin1776Route,
  BatteriesRoute: BatteriesRoute,
  CalculatorRoute: CalculatorRoute,
  CompanyRoute: CompanyRoute,
  ContactRoute: ContactRoute,
  FloridaRoute: FloridaRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SolarRoute: SolarRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
